### ISSUE TITLE
How can I run it in a subdirectory?

### ISSUE THREAD

**Issue by thomsna** [joemccann/dillinger#118]
I'm new to node.js, and I'm trying to get dillinger to run in a subdirectory, such as domain.com/dillinger. I'm using nginx as a proxy.
Has anyone tried this? I can't seem to figure out how.

**Comment by W-Floyd** [comment]
I tried doing this today, and I would say it's a Dillinger issue, of sorts - it has no option to specify a `baseURI` or similar. Every other application I've set up had such an option.

There is, however a way around it, though it feels so... wrong. Here's my working location block:

```
    location /markdown/ {
        proxy_set_header Accept-Encoding "";
        proxy_set_header Host $http_host/app1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect    off;
        add_header Pragma "no-cache";
        add_header Cache-Control "no-cache";

        proxy_pass         http://dillinger/;
        sub_filter 'action="/'  'action="/markdown/';
        sub_filter 'href="/'  'href="/markdown/';
        sub_filter 'src="/'  'src="/markdown/';
        sub_filter_once off;
    }
```

where dilinger had been set earlier like so:

```
upstream dillinger {
    server 127.0.0.1:8081;
}
```

I won't pretend to know Nginx that well, so credit where credit is due:

Pretty much all of the location block, as found [here](https://serverfault.com/a/813776).

To make the `sub_filter` work when compression is enabled, `proxy_set_header Accept-Encoding "";` must be set, as found [here](https://stackoverflow.com/a/36274259).

As far as I can tell, it's working okay, but no promises.

**Comment by joemccann** [comment]
Dillinger is just a web app so your NGINX configuration is actually the
issue.  When Dillinger runs it doesn't matter if it is the root of a
directory or within a subdirectory.

The only thing I could imagine is some path issues in Dillinger's codebase
but I haven't come across this in 6 years of Dillinger history.

**Comment by W-Floyd** [comment]
I'll admit, I only just noticed the `ngninx` directory in the repo, and it does indeed work as shown, but is no good when under a subdirectory.

With the following, rather standard nginx block:

```
    location /markdown/ {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_pass http://dillinger/;
        proxy_read_timeout      600s;
        proxy_send_timeout      600s;     
    }
```

![image](https://user-images.githubusercontent.com/11786132/30087205-abcb41d4-92e2-11e7-9c42-29762226a547.png)

![image](https://user-images.githubusercontent.com/11786132/30087156-5afee9a4-92e2-11e7-8c37-06ae54d23211.png)

As an example, https://github.com/joemccann/dillinger/blob/05d4a254420630f16a8957962167b7601d87a484/views/index.ejs#L46
is a culprit. When edited to read `css/app.css` rather than `/css/app.css`, it works under a subdirectory

Really though, I'm happy enough to let my instance run as is (though I'm not saying my nginx config is foolproof), and I'm not the one who's doing all the work, so I can't complain.

**Comment by joemccann** [comment]
yeah the infamous path error.  good luck mate!

**Comment by porjo** [comment]
In Golang this issue would be addressed by letting the user specify a prefix path - https://golang.org/pkg/net/http/#StripPrefix
```Go
// To serve a directory on disk (/tmp) under an alternate URL
// path (/tmpfiles/), use StripPrefix to modify the request
// URL's path before the FileServer sees it:
http.Handle("/tmpfiles/", http.StripPrefix("/tmpfiles/", http.FileServer(http.Dir("/tmp"))))
```
Not sure what the equivalent is in Node.js but there must be a way.
