### ISSUE TITLE
Import from GitHub with wrong encoding

### ISSUE THREAD

**Issue by Balancer** [joemccann/dillinger#270]
When I import a utf-8 encoded document from GitHub (example: https://github.com/Balancer/airbase/blob/master/readme.md ) in Dillinger.io I get garbage such as this: https://twitter.com/balancer73/status/537944695066746880

(Sorry for badly English)

**Comment by adamkowalewski** [comment]
I can confirm this problem (polish characters like ł,ź,ż,ć,ś,ą,ę are affected) and it seems to occur only when importing a file (reproduced today at dillinger.io). 

When I copy and paste the content manually it works fine. But when link my github account and then import a MD file, with such characters, encoding is broken, exactly like on previous pictures.

**Comment by AkselMeola** [comment]
I can too confirm this problem.

**Comment by Adhara3** [comment]
Yep, confirmed

**Comment by shark-oxi** [comment]
@shark-oxi join the conversation and confirm that importing UTF-8 file with french char doesn't work well.

**Comment by shark-oxi** [comment]
Maybe the question is *How to detect the encoding of a GitHib file in order to use the right encoding?*.

A very quick search give me those results : [encoding.js][1], [JsChardet][2], [
detect-character-encoding][3], etc ... or may be it's easy to implement.

[1]:https://github.com/polygonplanet/encoding.js
[2]:https://github.com/aadsm/jschardet
[3]:https://www.npmjs.com/package/detect-character-encoding

**Comment by julmot** [comment]
I've just imported a normal character `–` and it was replaced by `b--`. Very annoying problem!!!

**Comment by joemccann** [comment]
Not sure how this is still an issue...can you provide me with a markdown
example?
