### ISSUE TITLE
Can Dillinger be used as a front-end editor for Jekyll?

### ISSUE THREAD

**Issue by erlend-sh** [joemccann/dillinger#322]
I've posed this question on the Jekyll community forum. I would greatly appreciate your input:

https://talk.jekyllrb.com/t/an-idea-for-front-end-editing-in-jekyll-via-the-github-api-and-web-based-markdown-editors/737?u=erlend_sh

**Comment by joemccann** [comment]
yes it could!

**Comment by erlend-sh** [comment]
I hope you saw the "doable within the realm of reason"-part :stuck_out_tongue: 

- Do you know of any examples of Dillinger "embedded" into a page/app?
- What about "Create forks and submit pull requests via editor". How feasible does that sound?

**Comment by joemccann** [comment]
I do not know if it is being embedded anywhere.

Not sure what you mean by the second bullet point.

**Comment by erlend-sh** [comment]
For second point, I'm talking improving the editing experience for non-trusted users i.e. users who will have to create a pull request instead of committing directly.

For example, if you want to edit http://jekyllrb.com/docs/home/, you have to:
- Click "Improve this page"
 - Get redirected to GitHub.com
- Edit content
- Click to propose this change
- Click to make pull request

I'd like to take away the redirect step and combine the "propose change" and "make pull request" steps with the following workflow:

- Click "Improve this page" (opens Dillinger editor in-page)
- Edit content
- Save content as suggestion (in the background, Dillinger has created a fork of the repository and made a pull request for you).

**Comment by maguldemond** [comment]
This is very similar to what I'd really like to see too, which is easy editing for content editors on a client website using something like Dillinger or Stackedit, while insulating them from layout and design, html, and server code (Liquid, Razor, asp),  and preventing them from having to use version control like Git or Mercurial.

Basically, so the content editors can go edit text, add pages, images, etc., to a dev or stage instance, and not be able to mess up the code, while the designers and devs can write the css, html, and backend code and use version control and branching, on the same project. My company is being forced to use Kentico CMS for a major client because of this issue of content editors not being willing or competent or trusted enough (not sure which) to use version control. 

Prose.io does the easy static site editing, but you have to give Prose access to all of your git repos, and no paying client should allow that. You could install Prose on your own servers I suppose, but Dillinger and Stackedit seemed to be better developed editors.

The process I'd like to see:
* Content editors have a way to view folder structure on dev instance of website
* Content editor clicks on edit this page (opens Dillinger editor in-page) (or even Add New Page)
* Edit content
* Content gets committed to the git repo (private repo)
* commit triggers server side Jekyll to process new content and publishes back to dev instance of website.

We have build server jobs set up to push from dev to stage to prod, so we'd only need to get them to work on the dev instance I think.

thanks,
Marcel

**Comment by dalareo** [comment]
I am also trying to find/build something similar. Have you heard about http://prose.io/ ??

**Comment by ehausen** [comment]
How is it going? Has any alternatives for this kind of solution appeared during a year?

**Comment by joemccann** [comment]
I suppose you could render an html file to be embedded and inline the CSS
and JS but none of the cloud services or export features will work IIRC

On Sunday, May 15, 2016, Erik Hausen <notifications@github.com> wrote:

> How is it going? Has any alternatives for this kind of solution appeared
> during a year?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joemccann/dillinger/issues/322#issuecomment-219308296>
>


-- 
Sent from Joe In Real Life

**Comment by erlend-sh** [comment]
Well my initial understanding of Dillinger was probably a bit misguided. There's already a working proof-of-concept for the type of front-end editor I talked about here:

https://github.com/wiki-hub/wiki-hub

All it really needs is a Markdown editor, but Dillinger is quite a bit more than just a Markdown editor.
