### ISSUE TITLE
Granting Public-only Github repositories access

### ISSUE THREAD

**Issue by rngadam** [joemccann/dillinger#328]
Dillinger online editor instance requests Public+Private repositories access, but based on prose.io it is also possible to only grant access to public repositories. Having this option for Dillinger would make it seem "safer" to grant third-party app access than to all present and future private repositories.

![screen shot 2015-06-23 at 6 02 58 pm](https://cloud.githubusercontent.com/assets/538542/8303718/55459868-19d2-11e5-9376-adfe2af9e68b.png)

I'm able to obtain this behavior manually by changing the authorization URL scope parameter from repo to public_repo

![screen shot 2015-06-23 at 6 06 47 pm](https://cloud.githubusercontent.com/assets/538542/8303763/c02bf672-19d2-11e5-8620-84e924c48e86.png)

However, when I do Import from > Github > [Organization] > Repository > Branch the list of branches is empty (not sure why). Seems to relate to issue #264

**Comment by swang** [comment]
I am pretty sure when I implemented GitHub access there was no option to handle public/non-public access so it must have been added within the past year. Either that or I just went with one way since the UI for it wasn't really there.

I would help add it unfortunately the front-end has moved onto Angular, so I'm not really familiar with the that part of the code base anymore.

**Comment by joemccann** [comment]
@rngadam if you can take a stab at implementing this feature then I'll merge it

**Comment by aandis** [comment]
+1
