### ISSUE TITLE
Header formatting in preview incorrectly 

### ISSUE THREAD

**Issue by httpete-ire** [joemccann/dillinger#338]
I just noticed when I imported a readme file from github, the headlines are not formatting correctly in the preview window if a space is not preset between the # and the word. Github and Mou (markdown editor) both display this correctly.

Is this invalid markdown or does GitHub/Mou allow for both #heading and # heading?

**Comment by httpete-ire** [comment]
here's a quick screen cast of the issue http://quick.as/8wps6qpw

**Comment by Xarcell** [comment]
I think this is good and should be left this way. If fact, it was probably done this way intentionally. The thing to consider is what if in your writing you wanted to hashtag something? For example #Dillinger for twitter? Instead of the literal format, it would turn it into a heading. That would definitely be undesirable. By adding a space, it makes it quite clear that it should be a heading and without the space a hashtag of some sort(for twitter, Facebook, pinterest, etc).

Actually, github handles it the same way. See examples of what happens without and with space:
 
#man
# Man

This issue should be closed.
