### ISSUE TITLE
Scrolling with mouse wheel extremely slow in Chrome on CentOS x64 with scroll sync on

### ISSUE THREAD

**Issue by sisou** [joemccann/dillinger#516]
I just tested dillinger.io on my CentOS 7.2 with Chrome x64 (v49) and scrolling by mouse wheel is extremely slow when the scroll sync feature is on. Scrolling by pulling the scrollbars works fine.

It's *not* happening on my installed Firefox (v38.7).

**Comment by benjamin-albert** [comment]
This is caused by the [sync() function](https://github.com/joemccann/dillinger/blob/d5faaeae0cd8a350595e9298b067a1fc05382aaa/public/js/user/user.controller.js#L25) in `public/js/user/user.controller.js`.

this callback is triggered twice because it's bound to both sides.

The second invocation is the result of the first callback changing the second div's `.scrollTop` which also has this same `sync()` function bound to it.

Some browsers have an animated scroll effect, where it smears a single scroll event over multiple smaller scroll events.

In this case the second callback prevents the rest of the scroll events from being triggered which makes scrolling extremely slow.

Stay tuned for a pull request.

**Comment by benjamin-albert** [comment]
One other thing to note is that there is an [existing workaround](https://github.com/joemccann/dillinger/blob/d5faaeae0cd8a350595e9298b067a1fc05382aaa/public/js/user/user.controller.js#L25) in the code for this problem.

This workaround stopped working in recent versions of Chrome which add an animated scroll effect.

The existing workaround doesn't take into account animations that last longer than 10 milliseconds (like the one recently added to Chrome).
