### ISSUE TITLE
PDF Export. Add options for user: font size & Landscape / Portrait orientation

### ISSUE THREAD

**Issue by 3F** [joemccann/dillinger#637]
It would be great to see Landscape orientation at least.

Thanks for this project anyway :)

-----
The main problem is here:

* [Original.pdf](https://github.com/joemccann/dillinger/files/1232746/Original.pdf)
vs
* [Modified.pdf](https://github.com/joemccann/dillinger/files/1232747/Modified.pdf)

#### Portrait, with your increased size:
![portrait_origin_big_size](https://user-images.githubusercontent.com/3246589/29435346-60f0a718-83af-11e7-9a05-6615fd45b658.png)

#### Landscape:
![landscape_normal_size](https://user-images.githubusercontent.com/3246589/29435353-69ff6c90-83af-11e7-92dc-3ed7c5da41fd.png)

**Comment by attilaodry** [comment]
Same here! We are generating our documentation using md and dillinger is one of the best tool to use for this. The only issue we use to have, that we cannot format the size of the exported text and it will shows a badly formatted (line brakes) text.

If you could fix this issue with adding an exporter settings to set the font size it would be awesome!

I love the tool and really THANKS for it.

**Comment by joemccann** [comment]
This is a configuration with PhantomJS.  To upload your own configuration would require a ton of additional UI work.  I suggest we start with improving the PDF export now with a better configuration.  If someone wants to go ahead do the UI work too that'd be great!

**Comment by joemccann** [comment]
I improved the styling a bit.

**Comment by joemccann** [comment]
Can you let me know a preferred font size?

**Comment by joemccann** [comment]
@attilaodry

**Comment by attilaodry** [comment]
great news! thanks for your effort on this!
I'm not sure about the font size, but currently on my computer I see the website's preview with font size 11 (I guess), while the exported pdf version shows more like 16. 

If you can change the pdf document font size, that would be the best and it should then go lower (11 -12) to make a match with the web preview. If we could add this font size at the time of exporting (popup?) that would help a lot. Without it I would go with the same size that you can see on the webpage (or close enough).

Also the page size is an issue, since on the web the horizontal length are dynamic, so bigger browser windows will give you more space and longer lines, while in the pdf it will be shortened, causing different line breaks. A possibility of look at the preview with the same horizontal size / line length would be very handy. (toggle/flag to enable/disable that feature?)

**Comment by joemccann** [comment]
If you have the CSS you want I can try and add it.  I'm not sure why the font size isn't rendering as the same as the website as it is the same CSS being applied to the PDF?

**Comment by attilaodry** [comment]
I don't really have any preferred CSS, all I would like to see is similar font size and line sizes as in the preview :P
Btw, is the pdf exporter generate similar font size as in the preview for you? Wondering what settings we might differ.

**Comment by joemccann** [comment]
I'll try to figure out why the font is rendering so much bigger on the PDF.
It's the exact same CSS being applied but something must be getting dropped.
