### ISSUE TITLE
Unable to Sign-In with Google

### ISSUE THREAD

**Issue by matthewa150** [joemccann/dillinger#721]
It is the return of the "Sign in with Google temporarily disabled for this app" issue.
![oauth](https://user-images.githubusercontent.com/15635573/57723896-46925580-764f-11e9-938b-420c1c37263b.png)

**Comment by joemccann** [comment]
Ughhhh I've been trying to get them to fix this! Sorry but we're at the
mercy of Google.

**Comment by joemccann** [comment]
@matthewa150 are you still having this issue?

**Comment by matthewa150** [comment]
> @matthewa150 are you still having this issue?

@joemccann Alas - the problem persists for me. If it's been fixed for other people I can try a different network and/or account and see if that helps resolve the issue.

**Comment by joemccann** [comment]
Ugh so frustrating I've reached out to Google many times now. No response

**Comment by matthewa150** [comment]
@joemccann Don't worry about it haha, if it's on Google's end there is nothing you can do. (I'll still be using dillinger regardless)

**Comment by spentcartridge** [comment]
Any progress with Google on this issue? I'd really like to save docs to Drive.

**Comment by joemccann** [comment]
I've reached out to Google so many times I don't know what else to do. Will
keep trying

**Comment by spentcartridge** [comment]
Thx Joe-

**Comment by sqrrrl** [comment]
Sent details to Joe last night, reposting some details here for reference.

The issue appears to be that the app is only approved for login scopes (email/profile/etc), not drive. Since the app is asking for different scopes than approved for, it's being treated as unverified and subject to very restrictive sign in quotas. There's a 2nd problem that the drive scope being used is very broad and should be narrowed, otherwise the app will face [additional security reviews](https://cloud.google.com/blog/products/identity-security/enhancing-security-controls-for-google-drive-third-party-apps) as recently announced.

Suggested steps to fix this are:
- Change the oauth request to use the scope `https://www.googleapis.com/auth/drive.file`
- Change the import file code to [use the file picker](https://developers.google.com/drive/api/v3/picker) instead of using the Drive API to list files.
- Update the client ID in the developer console to include the drive scope as above.
- Request re-review of the app.

**Comment by joemccann** [comment]
Great thanks for this.

The problem with using the Filepicker is it completely breaks the branded
Dillinger experience.  I have the same issue with Dropbox.  The only way is
for me to able to keep the UX consistent is to be able to read and write to
a user's Drive.

Moreover, all of the source code is 100% open source and has been for
almost 9 years.

FWIW, I was granted everything before and it worked just fine.  Is the new
security review going to restrict me from allowing users to connect and
read/write to Drive?

Finally, I am currently able to read/write to Drive with no problem.  It's
just that the number of users allowed to do this is limited.  I just need
this changed to unlimited.

Thanks again!

**Comment by sqrrrl** [comment]
Yes, the picker does unfortunately create a branding/UX issue. The flip side, though, is using the full drive scope increases risk for users if there are any latent or newly introduced security vulnerabilities in the app that can expose their data. Personally I'd favor security over UX consistency here.

Anyway, the full scope is still allowed for productivity apps that require it while the user is present, but you'll be subject to a more stringent security review starting sometime next year and likely will receive a lot of push back about it. Being open source doesn't exempt the app from review. To the contrary, since your app proxies the Drive requests through a server and you're using a sensitive scope, you're likely to receive *more* scrutiny during review to ensure safe data handling practices.

**Comment by joemccann** [comment]
@matthewa150 @spentcartridge can you try now?  I believe the scopes issue has been resolved.

**Comment by spentcartridge** [comment]
Still getting the same error msg

**Comment by matthewa150** [comment]
@joemccann I still get the error message.

**Comment by joemccann** [comment]
try disconnecting and reconnecting your account @spentcartridge

**Comment by spentcartridge** [comment]
Same msg. Is it working for you?

**Comment by joemccann** [comment]
Ugh so frustrating. The scope is updated. I don't know what else to
do...let me try again with Google.

**Comment by spentcartridge** [comment]
Thanks for the effort Joe. I really, really like the interface of dillinger but I need to be able to save to Drive.

**Comment by joemccann** [comment]
@spentcartridge Is this still an issue?

**Comment by spentcartridge** [comment]
No, seems to be working

**Comment by joemccann** [comment]
Sweet!
